### ISSUE TITLE
Whan assigning a mapped output to an expression it cannot accept an array

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#451]
2022 Aug  5, 14:07:21.618 Engine 'enrolment PROD' Argument 1 passed to tool_dataflows\parser::has_expression() must be of the type 
string, array given, called in /var/www/moodle.local/admin/tool/dataflows/classes/parser.php on line 92 

ie with webservice step it should return an array of users, either 0 1 or many

```
webservice: core_user_get_users_by_field
user: admin
parameters: |
  field: email
  values: 
              - ${{ data.EMAIL }}
  
failure: abortstep
outputs:
  users: '${{ result }}'  <<--- this doesn't work
```
