### ISSUE TITLE
bug yaml config set at dataflow level isn't exported as yaml

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#477]
It is yaml inside a string in yaml eg

```
name: 'Al Test'
config: "data:\r\n  config: test"
steps:
  hourly_export:
    name: cron
    description: '25 mins past the hour'
    type: tool_dataflows\local\step\trigger_cron
    config:
```

and it should instead be
```
name: 'Al Test'
config:
  data:
   config: test
steps:
  hourly_export:
    name: cron
    description: '25 mins past the hour'
    type: tool_dataflows\local\step\trigger_cron
    config:
```

Tasks
* [ ] fix export
* [ ] make sure import still works
