### ISSUE TITLE
dml_exception / Error reading from database error 

### ISSUE THREAD

**Issue by marcghaly** [catalyst/moodle-tool_dataflows#537]
When running following flow

```
name: 'trichoice 10/08/2022 v1'
steps:
  user_get:
    name: 'user get'
    type: tool_dataflows\local\step\connector_curl
    config:
      curl: 'https://learn.bcpublicservice.gov.bc.ca/elm-moodle-cdata-endpoint/current_enrolment_info.json'
      destination: somedestination.json
      headers: ''
      method: get
      timeout: '0'
  json_read:
    name: 'json read'
    depends_on: user_get
    type: tool_dataflows\local\step\reader_json
    config:
      pathtojson: '${{ steps.user_get.config.destination }}'
      arrayexpression: value
      arraysortexpression: date_created
      sortorder: asc
  get_course_details:
    name: 'get course details'
    depends_on: json_read
    type: tool_dataflows\local\step\flow_web_service
    config:
      webservice: core_course_get_courses_by_field
      user: admin
      parameters: |
        field: idnumber
        value: 25375
        
      failure: abortflow
      outputs:
        courseid: '${{ result[''courses''][0][''id''] }}'
  get_users_ws:
    name: 'get users WS'
    depends_on: get_course_details
    type: tool_dataflows\local\step\flow_web_service
    config:
      webservice: core_user_get_users_by_field
      user: admin
      parameters: |
        field: email
        values: 
                    - ${{ data.EMAIL }}
        
      failure: abortflow
      outputs:
        users: '${{ result }}'
        usercount: '${{ count(result) }}'
        userid: '${{ result[0][''id''] }}'
  user_exists:
    name: 'drop or enrol'
    depends_on: get_users_ws
    type: tool_dataflows\local\step\flow_logic_case
    config:
      cases:
        'drop user': 'record.COURSE_STATE == ''Drop'' && steps.get_users_ws.usercount != 0'
        'create and enrol': 'record.COURSE_STATE == ''Enrol'' && steps.get_users_ws.usercount == 0'
        'only enrol': 'record.COURSE_STATE == ''Enrol'' && steps.get_users_ws.usercount != 0'
  create_user_ws:
    name: 'create user WS'
    depends_on: 'user_exists:2'
    type: tool_dataflows\local\step\flow_web_service
    config:
      webservice: core_user_create_users
      user: admin
      parameters: |
        users:
              - username: ${{ data.EMAIL }}
                firstname: ${{ data.FIRST_NAME }}
                lastname: ${{ data.LAST_NAME }}
                email: ${{ data.EMAIL }}
                createpassword: true
                firstnamephonetic: ${{ data.FIRST_NAME }}
                lastnamephonetic: test
                middlename: t
                alternatename: t
                auth: oauth2
                preferences: 
                                 -    type: auth_forcepasswordchange
                                      value: 0
        
      failure: abortflow
      outputs:
        userid: '${{ result[0][''id''] }}'
  enrol_user_ws:
    name: 'enrol user WS'
    depends_on: 'create_user_ws:1'
    type: tool_dataflows\local\step\flow_web_service
    config:
      webservice: enrol_manual_enrol_users
      user: admin
      parameters: |
        enrolments:
                0:
                  roleid: 5
                  userid: ${{ steps.create_user_ws.userid }}
                  courseid: ${{ steps.get_course_details.courseid }}
        
      failure: abortstep
  writter:
    name: writter
    depends_on: enrol_user_ws
    type: tool_dataflows\local\step\writer_stream
    config:
      streamname: test.txt
      format: json
  only_enrol:
    name: 'only enrol'
    depends_on: 'user_exists:3'
    type: tool_dataflows\local\step\flow_web_service
    config:
      webservice: enrol_manual_enrol_users
      user: admin
      parameters: |
        enrolments:
                0:
                    roleid: 5
                    userid: ${{steps.get_users_ws.userid}}
                    courseid: ${{ steps.get_course_details.courseid }}
        
      failure: abortstep
  writerr:
    name: writerr
    depends_on: 'only_enrol:1'
    type: tool_dataflows\local\step\writer_stream
    config:
      streamname: onlyenrol.ws
      format: json
  drop_user:
    name: 'drop user'
    depends_on: 'user_exists:1'
    type: tool_dataflows\local\step\flow_web_service
    config:
      webservice: enrol_manual_unenrol_users
      user: admin
      parameters: |
        enrolments:
            - userid: ${{ steps.get_users_ws.userid }}
              courseid: ${{steps.get_course_details.courseid }}
              
        
      failure: abortstep
  writer:
    name: writer
    depends_on: 'drop_user:1'
    type: tool_dataflows\local\step\writer_stream
    config:
      streamname: test.txt
      format: json
```

On this version of mysql: 

```
mysql Ver 14.14 Distrib 5.7.39, for Linux (x86_64) using  Editline wrapper
```
Following errors are triggered

```
2022 Aug 10, 10:48:22.540 Engine 'trichoice 10/08/2022 v1' Aborted: Error reading from database (You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 21
SELECT concat(sd.dependson, '|', sd.stepid) as id,
sd.dependson AS src,
sd.stepid AS dest
FROM mdl_tool_dataflows_step_depends sd
LEFT JOIN mdl_tool_dataflows_steps step ON step.id = sd.stepid
WHERE step.dataflowid = ?
ORDER BY sd.position ASC
-- line 294 of /admin/tool/dataflows/classes/dataflow.php: call to mysqli_native_moodle_database->get_records_sql()
-- line 120 of /admin/tool/dataflows/classes/dataflow.php: call to tool_dataflows\dataflow->get_edges()
-- line 471 of /admin/tool/dataflows/classes/dataflow.php: call to tool_dataflows\dataflow->__get()
-- line 120 of /admin/tool/dataflows/classes/dataflow.php: call to tool_dataflows\dataflow->get_step_order()
-- line 450 of /admin/tool/dataflows/classes/dataflow.php: call to tool_dataflows\dataflow->__get()
-- line 120 of /admin/tool/dataflows/classes/dataflow.php: call to tool_dataflows\dataflow->get_steps()
-- line 147 of /admin/tool/dataflows/classes/dataflow.php: call to tool_dataflows\dataflow->__get()
-- line 120 of /admin/tool/dataflows/classes/dataflow.php: call to tool_dataflows\dataflow->get_variables()
-- line 520 of /admin/tool/dataflows/classes/local/execution/engine.php: call to tool_dataflows\dataflow->__get()
-- line 87 of /admin/tool/dataflows/classes/local/execution/flow_engine_step.php: call to tool_dataflows\local\execution\engine->get_variables()
-- line 245 of /admin/tool/dataflows/classes/step.php: call to tool_dataflows\local\execution\flow_engine_step->get_variables()
-- line 126 of /admin/tool/dataflows/classes/step.php: call to tool_dataflows\step->get_config()
-- line 159 of /admin/tool/dataflows/classes/local/step/flow_logic_case.php: call to tool_dataflows\step->__get()
-- line 140 of /admin/tool/dataflows/classes/local/step/flow_logic_case.php: call to class@anonymous/home/moodle/public/admin/tool/dataflows/classes/local/step/flow_logic_case.php:140$f7->__construct()
-- line 61 of /admin/tool/dataflows/classes/local/execution/flow_engine_step.php: call to tool_dataflows\local\step\flow_logic_case->get_iterator()
-- line 423 of /admin/tool/dataflows/classes/local/execution/engine.php: call to tool_dataflows\local\execution\flow_engine_step->go()
-- line 378 of /admin/tool/dataflows/classes/local/execution/engine.php: call to tool_dataflows\local\execution\engine->execute_step()
-- line 120 of /admin/tool/dataflows/run.php: call to tool_dataflows\local\execution\engine->execute()
[array (
0 => '2',
)])
```
or

```
2022 Aug 9, 20:18:29.144 Engine 'dataflow' dml_exception: ERROR: Mixed types of sql query parameters!! in /home/moodle/public/lib/dml/moodle_database.php:915
Stack trace:
#0 /home/moodle/public/lib/dml/mysqli_native_moodle_database.php(1268): moodle_database->fix_sql_params()
#1 /home/moodle/public/admin/tool/dataflows/classes/dataflow.php(294): mysqli_native_moodle_database->get_records_sql()
#2 /home/moodle/public/admin/tool/dataflows/classes/dataflow.php(120): tool_dataflows\dataflow->get_edges()
#3 /home/moodle/public/admin/tool/dataflows/classes/dataflow.php(471): tool_dataflows\dataflow->__get()
#4 /home/moodle/public/admin/tool/dataflows/classes/dataflow.php(120): tool_dataflows\dataflow->get_step_order()
#5 /home/moodle/public/admin/tool/dataflows/classes/dataflow.php(450): tool_dataflows\dataflow->__get()
#6 /home/moodle/public/admin/tool/dataflows/classes/dataflow.php(120): tool_dataflows\dataflow->get_steps()
#7 /home/moodle/public/admin/tool/dataflows/classes/dataflow.php(147): tool_dataflows\dataflow->__get()
#8 /home/moodle/public/admin/tool/dataflows/classes/dataflow.php(120): tool_dataflows\dataflow->get_variables()
#9 /home/moodle/public/admin/tool/dataflows/classes/local/execution/engine.php(520): tool_dataflows\dataflow->__get()
#10 /home/moodle/public/admin/tool/dataflows/classes/local/execution/flow_engine_step.php(87): tool_dataflows\local\execution\engine->get_variables()
#11 /home/moodle/public/admin/tool/dataflows/classes/step.php(245): tool_dataflows\local\execution\flow_engine_step->get_variables()
#12 /home/moodle/public/admin/tool/dataflows/classes/step.php(126): tool_dataflows\step->get_config()
#13 /home/moodle/public/admin/tool/dataflows/classes/local/step/flow_logic_case.php(159): tool_dataflows\step->__get()
#14 /home/moodle/public/admin/tool/dataflows/classes/local/step/flow_logic_case.php(140): class@anonymous->__construct()
#15 /home/moodle/public/admin/tool/dataflows/classes/local/execution/flow_engine_step.php(61): tool_dataflows\local\step\flow_logic_case->get_iterator()
#16 /home/moodle/public/admin/tool/dataflows/classes/local/execution/engine.php(423): tool_dataflows\local\execution\flow_engine_step->go()
#17 /home/moodle/public/admin/tool/dataflows/classes/local/execution/engine.php(378): tool_dataflows\local\execution\engine->execute_step()
#18 /home/moodle/public/admin/tool/dataflows/run.php(120): tool_dataflows\local\execution\engine->execute()
#19 {main}
```

I suspect this is a crosscompatibility issue, as this flow is running without issue on pgsql, this seems to be triggered here https://github.com/catalyst/moodle-tool_dataflows/blob/MOODLE_35_STABLE/classes/dataflow.php#L285
